config/routes.rb
Rails.application.routes.draw do

  devise_for :user

  root to: 'application#index'
  resources :reports do
    resources :slack_channels
    get 'slack_webhook_determination', on: :collection
  end

  resources :incoming_mails, only: [:create]
end

app/models/slack_channel.rb
class SlackChannel < ApplicationRecord
  BOT_NAME = 'EmailPoster.co'

  belongs_to :report, optional: true
end

app/controllers/slack_channels_controller.rb
class SlackChannelsController < ApplicationController
  before_action :set_slack_channel, only: [:show, :edit, :update, :destroy]
  before_action :set_current_report_id

  def index
    @slack_channels = SlackChannel.all
  end

  def show
  end

  def new
    @slack_channel = SlackChannel.new
    @slack_channel.report_id = @report_id
  end

  def edit
  end

  def create
    @slack_channel = SlackChannel.new(slack_channel_params)

    respond_to do |format|
      if @slack_channel.save
        format.html { redirect_to report_path(@slack_channel.report_id), flash: { success: 'Slack channel was successfully created.' } }
        format.json { render :show, status: :created, location: @slack_channel }
      else
        format.html { render :new }
        format.json { render json: @slack_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @slack_channel.update(slack_channel_params)
        format.html { redirect_to report_path(@slack_channel.report_id), flash: { success: 'Slack channel was successfully updated.' } }
        format.json { render :show, status: :ok, location: @slack_channel }
      else
        format.html { render :edit }
        format.json { render json: @slack_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    report_id = @slack_channel.report_id
    @slack_channel.destroy
    respond_to do |format|
      format.html { redirect_to report_path(report_id), flash: { success: 'Slack channel was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  private
    def set_slack_channel
      @slack_channel = SlackChannel.find(params[:id])
    end

    def set_current_report_id
      @report_id = params[:report_id]
    end

    def slack_channel_params
      params.require(:slack_channel).permit(:webhook_url, :slack_message_text, :report_id)
    end
end

app/helpers/slack_channels_helper.rb
module SlackChannelsHelper
end

app/views/slack_channels/_form.html.erb
<%= form_for([slack_channel.report, slack_channel]) do |f| %>
  <% if slack_channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slack_channel.errors.count, "error") %> prohibited this slack_channel from being saved:</h2>

      <ul>
      <% slack_channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :report_id %>

  <div class="form-group">
    <%= f.label :slack_message_text %>
    <div class="input-group col-md-6">
      <%= f.text_field :slack_message_text, autocomplete: "off", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :webhook_url %>
    <div class="input-group col-md-6">
      <%= f.text_field :webhook_url, autocomplete: "off", class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Submit', class: "btn btn-success" %>
  </div>
<% end %>

app/views/slack_channels/_index.html.erb
<h1>Slack Channels</h1>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>Webhook url</th>
    <th style="width: 14%">Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @slack_channels.each do |slack_channel| %>
      <tr>
        <td><%= slack_channel.webhook_url %></td>
        <td>
          <%= link_to 'Show', edit_report_slack_channel_path(@report_id, slack_channel), class: 'btn btn-primary' %>
          <%= link_to 'Destroy', report_slack_channel_path(@report_id, slack_channel), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>

app/views/slack_channels/edit.html.erb
<div class="container reports">
  <div>
    <h1>Editing Slack Channel</h1>

    <%= render 'form', slack_channel: @slack_channel %>

    <%= link_to 'Back', report_path(@report_id) %>
  </div>
</div>

app/views/slack_channels/index.html.erb
<div class="container reports">
  <%= render 'index'%>
</div>

app/views/slack_channels/new.html.erb
<div class="container reports">
  <div>
    <h1 class="title">New Slack Channel</h1>
      <%= render 'form', slack_channel: @slack_channel, report_id: @report_id %>

      <%= link_to 'Back', report_path(@report_id) %>
  </div>
</div>

app/views/slack_channels/show.html.erb
<%= link_to 'Edit',  edit_report_slack_channel_path(@report_id, @slack_channel) %> |
<%= link_to 'Back',  report_path(@report_id) %>