config/routes.rb
Rails.application.routes.draw do

  devise_for :user

  root to: 'application#index'
  resources :reports do
    resources :slack_channels
    get 'slack_webhook_determination', on: :collection
  end

  resources :incoming_mails, only: [:create]
end

app/models/report.rb
class Report < ApplicationRecord
  EMAILTO_POSTFIX = '@inbound.emailposter.co'

  attr_writer :email_to_prefix

  enum processing_type: [:pdf, :body]

  before_validation :ensure_email_to

  belongs_to :user, optional: true
  has_many :slack_channels
  has_many :emails

  validates :title, presence: true
  validates :email_to,
            format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: 'Incorrectly (.. @ ... com)'},
            uniqueness: {message: 'the email address already exists'}

  def email_to_prefix
    @email_to_prefix ||= email_to.split('@')[0] rescue nil
  end

  private

  def ensure_email_to
    if email_to_prefix.blank?
      self.email_to = SecureRandom.hex(12) + EMAILTO_POSTFIX
    else
      self.email_to = email_to_prefix.split('@')[0] + EMAILTO_POSTFIX
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # before_action :check_admin
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_filter :set_report_id, only: [:show]

  def index
    @reports = current_user.reports
  end


  def show
    @emails = Email.where(report_id: @report.id)
    @slack_channels = SlackChannel.where(report_id: @report.id)
    @report_id = @report.id
  end


  def new
    @report = Report.new
  end


  def edit
  end


  def create
    @report = current_user.reports.build(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, flash: { success: 'Report was successfully created.' } }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, flash: { success: 'Report was successfully updated.' } }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, flash: { success: 'Report was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  def slack_webhook_determination
    if params[:code].present?
      SlackIntegration.new.determine_webhook(cookies[:report], params[:code])
      redirect_to report_path(cookies[:report])
    else
      redirect_to root_path
    end
  end

  private

    def set_report
      @report = Report.find(params[:id])
      authorize! :manage, @report
    end

    def report_params
      params.require(:report).permit(:title, :email_to_prefix, :processing_type)
    end

    def check_admin
      redirect_to root_path unless current_user.is_admin
    end

    def set_report_id
      cookies[:report] = { value: params[:id] }
    end

end

app/helpers/reports_helper.rb
require "uri"
require "net/http"

module ReportsHelper
  def user_images user
    content_tag :div, class: 'row user-images' do
      user.emails.each do |email|
        email.attachments.each do |attach|
          concat user_image attach.url
        end
      end
    end
  end

  def user_image image_path
    image_tag "https://process.filestackapi.com/#{TestApp::Application.config.filestack_api_secret}/output=format:jpg,density:30/#{image_url(image_path)}",
              class: 'img-rounded'
  end

  private

  def image_url image_path
    TestApp::Application.config.host + image_path
  end
end

app/views/reports/_form.html.erb
<%= form_for(report) do |f| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li ><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <div class="input-group col-md-6">
      <%= f.text_field :title, autocomplete: "off", class: "form-control" %>
    </div>
  </div>

  <% unless report.new_record? %>
    <div class="form-group">
      <%= f.label :email_to %>
      <div class="input-group col-md-6">
        <%= f.text_field :email_to_prefix, autocomplete: "off", class: "form-control" %>
        <span class="input-group-addon"><%=Report::EMAILTO_POSTFIX%></span>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-xs-9">
          <div>
            <%= f.radio_button :processing_type, 'pdf' %>
            <%= label :processing_type, 'post image of pdf report' %>
          </div>
          <div>
            <%= f.radio_button :processing_type, 'body' %>
            <%= label :processing_type, 'post image of email body' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit 'Submit', class: "btn btn-success"  %>
  </div>
<% end %>

app/views/reports/_history.html.erb
<div class="container reports">
  <h1>History</h1>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Sender</th>
      <th>Subject</th>
      <th>Date</th>
      <th>Attachment name</th>
      <th>Attachment type</th>
      <th>Status</th>
      <th>Received error</th>
    </tr>
    </thead>
    <tbody>
      <% emails.each do |email| %>
        <tr>
          <td><%= email.email_from %></td>
          <td><%= email.subject %></td>
          <td><%= email.created_at %></td>
          <td>
            <% email.img_urls.each do |img| %>
              <%= img['filename'] %>
            <% end %>
          </td>
          <td>
            <% email.img_urls.each do |img| %>
                <%= img['type'] %>
            <% end %>
          </td>
          <td><%= email.status_formated %></td>
          <td><%= email.error_message %></td>
        </tr>
        <% unless email.img_urls.blank? %>
          <% email.img_urls.each do |img| %>
            <tr>
              <td colspan="7" style="text-align: center;"><img src='<%= img['url'] %>' class="img-rounded"></td>
            </tr>
          <% end %>
        <%end%>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reports/edit.html.erb
<div class="container reports">
  <div>
    <h1>Editing Report</h1>
    <%= render 'form', report: @report %>

    <div class="back-button">
      <%= link_to 'Show', @report %> |
      <%= link_to 'Back', reports_path %>
    </div>
  </div>
</div>

app/views/reports/index.html.erb
<div class="container reports">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Title</th>
        <th>Email_to</th>
        <th style="width: 25%">Actions</th>
      </tr>
    </thead>
     <tbody>
     <h1>Reports</h1>
      <% @reports.each do |report| %>
        <tr>
          <td><%= report.title%></td>
          <td><%= report.email_to%></td>
          <td style="text-align: center">
            <%= link_to 'Show', report, class: 'btn btn-primary' %>
            <%= link_to 'Edit', edit_report_path(report), class: 'btn btn-warning' %>
            <%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New Report', new_report_path , class: 'btn btn-primary'%>
</div>

app/views/reports/new.html.erb
<div class="container reports">
  <div>
    <h1 class="title">New report</h1>
    <%= render 'form', report: @report %>

    <%= link_to 'Back', reports_path, class: 'back-button' %>
  </div>
</div>

app/views/reports/show.html.erb
<div class="container reports">
  <div>
    <h1 class="title">Show report</h1>
      <h4>Title: <%= @report.title%></h4>
      <h4>Email to: <%= @report.email_to%></h4>
    </br>
    <div class="actions">
      <%= link_to 'Edit', edit_report_path(@report), class: 'btn btn-warning' %>
      <%= link_to 'Destroy', @report, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      <%= link_to 'Back', reports_path%>
    </div>
  </div>
  <div>
    <%= render 'slack_channels/index' %>
    <a href="https://slack.com/oauth/reflow?client_id=<%= TestApp::Application.config.slack_client_id %>&scope=incoming-webhook">
      <img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x" />
    </a>
  </div>
</div>
<%= render 'history', reports: @report, emails: @emails%>